plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.36'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = '1.5.0'
group = 'com.example.teleportblock'

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }
    maven {
        name = "shedaniel Maven"
        url = "https://maven.shedaniel.me/"
    }
    maven {
        name = "Create Maven"
        url = "https://maven.createmod.net"
    }
    maven {
        name = "Registrate Maven"
        url = "https://maven.ithundxr.dev/snapshots"
    }
    maven {
        name = "Twelve Iterations Maven"
        url = "https://maven.twelveiterations.com/repository/maven-public/"
        content {
            includeGroup "net.blay09.mods"
        }
    }
    maven {
        name = "RyanHCode Maven"
        url = "https://maven.ryanhcode.dev/releases"
        content {
            includeGroup "dev.ryanhcode.sable-companion"
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly "maven.modrinth:jade:15.5.2+neoforge"
    compileOnly "curse.maven:jei-238222:7420587"
    compileOnly "maven.modrinth:emi:1.1.22+1.21.1+neoforge"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:15.0.140"
    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:16.0.799"
    compileOnly "curse.maven:waystones-245755:6447120"
    compileOnly("com.simibubi.create:create-1.21.1:6.0.10-280:slim") { transitive = false }
    compileOnly "net.createmod.ponder:ponder-neoforge:1.0.82+mc1.21.1"
    compileOnly "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1:1.0.6"
    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:[1.5,)")) {
        version {
            prefer "1.5.0"
        }
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}