modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "teleportblock"
version = "1.0.0"
displayName = "Teleport Block"
description = "A block that teleports players."

[[dependencies.teleportblock]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "jade"
type = "optional"
versionRange = "[15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "sable"
type = "optional"
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "jei"
type = "optional"
versionRange = "[19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[16,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.teleportblock]]
modId = "ftbchunks"
type = "optional"
versionRange = "[2101,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleportblock]]
modId = "emi"
type = "optional"
versionRange = "[1.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.teleportblock]]
modId = "journeymap"
type = "optional"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "CLIENT"